### ISSUE TITLE
edeint clip parameter like yadifmod2

### ISSUE THREAD

**Issue by realfinder** [Asd-g/AviSynth-BWDIF#3]
Hi,
I wonder if it possible to add edeint to BWDIF so we can use nnedi3 or something for spatial predictions for better quality

thanks

**Comment by Asd-g** [comment]
Please try this test version - https://gofile.io/d/o5VcBd
Use only opt=0, the name of the additional parameter is edeint.

**Comment by realfinder** [comment]
thanks, but when using edeint there are some artifacts that similar to yadif family but even worst

https://www.solidfiles.com/v/6dVAg8NjvA257

```
LoadPlugin("BWDIF.dll")
ffms2("a test.mkv")
AssumeTFF()
BWDIF(-2,opt=0,edeint=nnedi3(-2))
```

see frame 18 (00:00:00.300) for example

**Comment by Asd-g** [comment]
Please try this version - https://gofile.io/d/AQZJJs
Can you share the unfiltered video?

**Comment by realfinder** [comment]
thanks, this seems fine, I will also do more test with it

it's unfiltered, it's from DVD with just trim and lossless encode, anyway it was from line0 IIRC
edit: same sample as https://web.archive.org/web/20160927234818/http://forum.doom9.org/showthread.php?t=173029

and if you still need it I will post it (it was just the opening of that Anime)

**Comment by realfinder** [comment]
I find it without edeint it give

![image](https://user-images.githubusercontent.com/2512153/90982109-ab846d00-e56d-11ea-9ba0-1cd396a6f8f4.png)

**Comment by realfinder** [comment]
I did test with that VHS sample https://forum.doom9.org/showthread.php?t=181735

```
AVISource("amarec(20200806-1406)_sample.avi")
converttoyv16
AssumeTFF()
nnclip=nnedi3(-2)
BWDIF(-2,edeint=nnclip)
```

![image](https://user-images.githubusercontent.com/2512153/90982337-32861500-e56f-11ea-9cc8-e3a4fac1017e.png)

```
AVISource("amarec(20200806-1406)_sample.avi")
converttoyv16
AssumeTFF()
nnclip=nnedi3(-2)
yadifmod2(mode=1,edeint=nnclip)
```

![image](https://user-images.githubusercontent.com/2512153/90982366-71b46600-e56f-11ea-8e05-b62645ebc39b.png)

with old BWDIF(-2)
![image](https://user-images.githubusercontent.com/2512153/90982495-18990200-e570-11ea-9b56-1e0652eace15.png)

it seems BWDIF still not use edeint well

**Comment by Asd-g** [comment]
What's the frame number?

```
LWLibavVideoSource("amarec(20200806-1406)_sample.avi")
AssumeTFF()
BWDIF(-2,opt=0,edeint=nnedi3(-2)) #yadifmod2(mode=1, edeint=nnedi3(-2)) #BWDIF(-2)
```
Frame 538 - https://images2.imgbox.com/8d/b5/tLUc6LgR_o.png (BWDIF(-2,opt=0,edeint=nnedi3(-2)))
https://images2.imgbox.com/c4/b2/hhcsjOgc_o.png (yadifmod2(mode=1, edeint=nnedi3(-2)))
https://images2.imgbox.com/cc/f3/RKBsblS5_o.png (BWDIF(-2))

**Comment by realfinder** [comment]
yes, opt=0 fix it, I was think that the beta is ready for any opt

**Comment by Asd-g** [comment]
Yes, only opt=0.
I will finish it later.

**Comment by Asd-g** [comment]
Please try version 1.2.0

**Comment by realfinder** [comment]
all old problems seems fixed now, thanks
