### ISSUE TITLE
Weave threshold parameter

### ISSUE THREAD

**Issue by flossy83** [Asd-g/AviSynth-BWDIF#4]
Hello, I was wondering if it's possible to add some kind of weave threshold parameter for the double framerate mode?  I think it is too quick to interpolate -- the tiniest amount of video noise or camera wobble sets pixels into interpolation mode.   I think image quality would be greatly improved if the threshold was a bit higher.   Although, I am ignorant about how bwdif works so I'm not sure it's even possible without writing lots of new code.   I was hoping there was already a parameter in the existing code that could simply be exposed to the end user.  Thanks.

**Comment by Asd-g** [comment]
Hi,

Try the attached version to see if this is what you want. There is new param `thr`. Default is 0 and it has the behavior of the official release. Try with higher values.

[BWDIF.zip](https://github.com/Asd-g/AviSynth-BWDIF/files/9895096/BWDIF.zip)

**Comment by flossy83** [comment]
Very happy with this, thank you.  It seems to be working nicely with a value of 3-5.

On the test pattern with 1px alternating white and black lines, pattern is perfect and not flickering.

On static scene with camera noise, it is weaving still despite the noise -- good.

Although value of 3-5 seems to be good, it would be even better if there was a debug param like TDeint(map=2) to highlight interpolated pixels to help us set the threshold precisely for certain content.

Have tried with bwdif(edeint=BlankClip()) and Subtract(last, bwdif()) but result is not as expected.

Thanks

**Comment by Asd-g** [comment]
Try 1.2.2.

**Comment by flossy83** [comment]
Thanks, the debug feature is working nicely, but it seems you've changed something else where it now requires _IsFieldBased otherwise the video output is blank.   For reasons I don't understand it seems to cause incompatibility when using LWLibavVideoSource(repeat=true) or FFmpegSource2(rffmode=1) with an interlaced file with repeat flags.

Such test clip: https://drive.google.com/file/d/1dwa7gB3HHuSPXroA2ifm4LtLX0fSs2bM/view?usp=share_link

This issue seems to have been introduced in the latest 1.2.2 as it is not present in the BWDIF.zip in post#2 of this thread.

**Comment by Asd-g** [comment]
The reason that you have issues is because that clip has `_FieldBased` frame property - 0 (progressive). Also it has wrong `_Matrix` frame property - rgb.

In order to use the latest version you have to put either `propset("_FieldBased", 2)` or `propDelete("_FieldBased")` before BWDIF.

Please read README.md and the info about the `field` parameter.

**Comment by flossy83** [comment]
I think that was the clipping software (XMediaRecode) which caused that incorrect _Matrix frame property, as the source from which I clipped it is reporting "Matrix = 2 = unspec" with propShow().    The source was remuxed directly from my DVD using MakeMKV and I'm not sure if there should be any matrix metadata in the DVD's MPEG2 stream.   In any case I happen to end up with correct colour decoding since MadVR guesses correctly based on the resolution and framerate (ctrl+J: "matrix bt.601 (best guess)").

Thanks for clearing that up, I guess I need to remember to set the right field properties.  I did actually try AssumeTFF/BFF() and AssumeFrame/FieldBased() before writing my last reply and could not get it to work.

As long as you're aware of this behaviour and it is intentional and that others like TDeint, Yadif, Bob will process the file regardless of its frame property.

**Comment by Asd-g** [comment]
DVD's MPEG2 streams, depending on what source filter is used, usually have _Matrix = 2/5.

> I did actually try AssumeTFF/BFF() and AssumeFrame/FieldBased() before writing my last reply and could not get it to work.

Delete `_FieldBased` prop (`propDelete("_FieldBased")`) in order to use AssumeTFF/BFF().

Frame properties (when they are supported) should have precedence over the clip properties (AssumeTFF/BFF(), AssumeFrame/FieldBased()).

I will update yadifmod2 soon in order to read the frame properties.

**Comment by flossy83** [comment]
I should probably mention that clip is from a "soft telecined" NTSC DVD where the frames are supposedly encoded as progressive 24p and the source filter is supposed to use frame flags to reconstruct 60i from it.   Maybe that is causing some confusion with the "fieldbased" parameter?    

The reason I want to deinterlace it is because even though it's 24p it still contains these split-second combing artefacts on some scene splices (there are 2 of them in the test clip).  So this might be a scenario where even though it's progressive or flagged as such, I still want to deinterlace to remove those split-second combing artefacts.

**Comment by Asd-g** [comment]
> I should probably mention that clip is from a "soft telecined" NTSC DVD where the frames are supposedly encoded as progressive 24p and the source filter is supposed to use frame flags to reconstruct 60i from it.   Maybe that is causing some confusion with the "fieldbased" parameter?

In that case you should manually change/delete `_FieldBased`.

**Comment by flossy83** [comment]
Just wanted to comment on this again.

Changing the _FieldBased prop needs to be done every frame, so it requires knowledge of advanced scripting techniques like ScriptClip or FrameEvaluate.  

There is quite a bit of soft telecined DVD content which is _FieldBased=0 and has combed frames on scene changes -- deinterlacers are often used to fix this type of content.  Examples in my DVD collection: MacGyver the TV movies, Caroline in the City, Cowboy Bebop.  These are MPEG2 remuxes from my physical copies, not some random file that someone made.

The display of the error message complaining about _FieldBased is not working with soft telecined clips on my system, so I had no idea what to do or how to fix it.   I either get a frozen frame or blank frame with nothing overlayed on top. I just happened to test it on another 1080p file and that gave me the error message that lead me in the right direction.  

If the user is not aware of the _FieldBased requirement , the clip can randomly freeze in places where bwdif is conditionally employed at a later point in the video, such as when using TFM(clip2=bwdif) or TDeint(edeint=bwdif) and combing is detected.  This caused me to think I had done something else wrong, or that I was trying to be too clever with my scripting and confused Avisynth (again, I got no error message from bwdif saying that _FieldBased must be >0).

As you have mentioned, these can be worked around by setting field=0/1/2/3 instead of -1/-2.  Is that field order locked for the duration of the clip?  What if the field order changes dynamically...I have a clip that changes between 0 (prog) and 1/2 (tff/bff) dynamically.

**Comment by Asd-g** [comment]
> I was trying to be too clever with my scripting and confused Avisynth (again, I got no error message from bwdif saying that _FieldBased must be >0).

What's your piece of the script that makes bwdif to not give error about `_FieldBased`?

Set `field` >= 0 forces the field order and ignores anything else (`_FieldBased` / `GetParity`).

If the field order changes dynamically and you don't want to rely on `_FieldBased`: set `field` = -1/-2 and delete `_FieldBased`. That way `GetParity` is checked every frame.

**Comment by flossy83** [comment]
Regardless of my script, I still don't get the error message on soft telecined stuff like [this clip](https://drive.google.com/file/d/1dwa7gB3HHuSPXroA2ifm4LtLX0fSs2bM/view?usp=share_link).   It just freezes on the first frame and hangs there, and on some other clips its just a blank screen.    I play my .avs files in MPC-HC so maybe that has something to do with it.

[Here](https://drive.google.com/file/d/1lHB_EPFEKAQEiKab5LlYq0EyY9OOObeT/view?usp=share_link) is a clip with dynamic field order.  With current version bwdif it seems I can't deinterlace that properly anymore.  In other words, I want bwdif to see the field order changing and obey that in real time, which it does with the old version.

**Comment by flossy83** [comment]
I've noticed LWlibavVideo seems to be the only source filter which sets the _FieldBased frame property on a per-frame basis on those clips.   The others just don't set it at all, so BWDIF works with field=-1/-2 when not using LWlibav.     

Perhaps when playback begins with LWlibav, the first few frames just happen to have _FieldBased !=0, so those get rendered, then a few frames later it reaches some frames with _FieldBased=0, BWDIF then displays its error message but doesn't get displayed cause the previously rendered frames are obscuring it?

**Comment by Asd-g** [comment]
> Regardless of my script, I still don't get the error message on soft telecined stuff like [this clip](https://drive.google.com/file/d/1dwa7gB3HHuSPXroA2ifm4LtLX0fSs2bM/view?usp=share_link). It just freezes on the first frame and hangs there, and on some other clips its just a blank screen. I play my .avs files in MPC-HC so maybe that has something to do with it.

Then blame MPC-HC that doesn't pass the avs runtime error. [Here](https://i.imgaa.com/2022/11/20/6379847269735106698831.png) what I get in AvsPmod.

> [Here](https://drive.google.com/file/d/1lHB_EPFEKAQEiKab5LlYq0EyY9OOObeT/view?usp=share_link) is a clip with dynamic field order. With current version bwdif it seems I can't deinterlace that properly anymore. In other words, I want bwdif to see the field order changing and obey that in real time, which it does with the old version.

I will repeat myself from my previous comment - "If the field order changes dynamically and you don't want to rely on _FieldBased: set field = -1/-2 and delete _FieldBased. That way GetParity is checked every frame."
So with this clip just do:
```
LWLibavVideoSource()
propDelete("_FieldBased")
bwdif()
```
Btw the old bwdif wouldn't see the dynamically change of the field because it reads the order only from the first frame. The latest bwdif read the field order for every frame.

**Comment by flossy83** [comment]
Thanks, I went back and re-tested with the old bwdif using field=-2 and that still gets the field order wrong on some sequences, while Bob() and TDeint() gets it right, so I think it might be a separate issue with bwdif not interpreting field order quite correctly.  Deleting _FieldBased and using field=-2 doesn't get all sequences right either.

For more efficient debugging here is a shorter version of the clip queued up to some sequences where field order changes are causing problems: https://drive.google.com/file/d/1wVvHnNjOqlMY985QMQyxbg35lhAAi0tl/view?usp=share_link

Debugging script:
```
file = "horrid clip.mkv"
LWlibavVideoSource(file, repeat=false)  #repeat=true not working with current build

ScriptClip(last, 
\ """
	propDelete("_FieldBased")  
	
	fieldbased = propGetAny("_FieldBased")
	parity = GetParity(current_frame)
	
	if (!IsInt(fieldbased)){fieldbased="undefined"}
	else if (fieldbased==0){ fieldbased = "progressive" }
	else if (fieldbased==1){fieldbased = "bottom field first"}
	else if (fieldbased==2){fieldbased = "top field first"}
	
	if (!IsBool(parity)){parity="undefined"}
	else if (parity==true){parity = "top field first"}
	else if (parity==false){parity = "bottom field first"}

	SubTitle("_FieldBased: " + fieldbased + "\n" + "GetParity:   " + parity, font="courier new", size=24, lsp=10)
	
\ """)

# bob()			# no issues
# TDeint(mode=1)	# no issues
bwdif(field=-2, thr=2)	# field order problems
```


I presume when _FieldBased = progressive, that means field order doesn't matter?  Since there are some frames where _FieldBased=progressive and GetParity is either TFF/BFF.

edit: btw LWLibavVideoSource appears to be the only Avisynth source filter that updates the field order on a per-frame basis, so I think it is the only Avisynth source filter that would even be capable of playing this clip correctly.   I'm curious to see what the result would be if we enable repeat field flags with LWLibavVideoSource, but that feature isn't working with this clip right now.

**Comment by Asd-g** [comment]
[This clip](https://drive.google.com/file/d/1wVvHnNjOqlMY985QMQyxbg35lhAAi0tl/view?usp=share_link) has parity false for all frames except the last one. What's the exact frame number you have issues? What I used to quickly check the clip:
```
s=LWLibavVideoSource("horrid clip.mkv")

# Tdeint
td0 = TDeint(s, mode=1)
td = Subtitle(td0, "TDeint")

# BWDIF
bw0 = propDelete(s, "_FieldBased")
bw0 = BWDIF(bw0, -2)
bw = Subtitle(bw0, "BWDIF")

# Bob
b0 = Bob(s)
b = Subtitle(b0, "Bob")

# Border
BlankClip(clip=s, length=846, width=10, colors=[128, 128, 128])
border = KillAudio()

StackHorizontal(td, border, bw, border, b)
```

Edit: I found the double rate bug. You can try 1.2.3.

**Comment by flossy83** [comment]
BWDIF is getting the field order correct when using LwlibAVvideo(repeat=true) but with repeat=false it doesn't, while the other deinterlacers do.    

With repeat=false, the parity is changing per frame which you can only see with runtime function ScriptClip.

Honestly I am so confused by all this, I might just give up.

**Comment by Asd-g** [comment]
> Edit: I found the double rate bug. You can try 1.2.3.

Did you try [the latest version](https://github.com/Asd-g/AviSynth-BWDIF/releases/tag/1.2.3)? It should be ok with `repeat=false` too.

**Comment by flossy83** [comment]
Yes latest version.  But LwLibav is playing the clip too fast with repeat=false so maybe its a lwlibav issue.

With repeat=false, did you step through each frame one at a time to check the direction of the credits is always scrolling in 1 direction?   Because you could miss that if not stepping through frame by frame.   A couple of times I thought it looked "ok" but then stepping through revealed the direction was changing ("two steps forward, one step back").

**Comment by Asd-g** [comment]
With `repeat=false` what's the exact frame number that bwdif(-2) is wrong and tdeint(mode=1) is ok?

**Comment by flossy83** [comment]
Ok, I must have done something wrong as with current version + propdelete(_fieldbased) + field=-2, the clip plays properly.   Thanks for that!

But the thing is, I still think it's worth having a field=-2 mode without requiring deleting _FieldBased, since I need to use _FieldBased to detect orphaned fields.   eg. in the [laundry clip](https://drive.google.com/file/d/1dwa7gB3HHuSPXroA2ifm4LtLX0fSs2bM/view) with LwLibavVideoSource(repeat=false), the _FieldBased prop switches from "progressive" to "top field" just for those orphaned fields on scene change, allowing me to deinterlace only those frames.

But, lwlibav doesn't work properly with repeat=false (it plays too fast) so it's kind of a moot point unless lwlibav is fixed.

**Comment by flossy83** [comment]
Apologies, it seems the editing software I used (XMediaRecode) to cut the short clip from the full episode has mucked up the repeat field flags and that was causing a lot of issues.   I wouldn't trust those short clips at all, sorry for wasting your time.

**Comment by flossy83** [comment]
Random idea...

```
if (field==-1 || field==-2){

	if (_FieldBased==0)  # 0=progressive
		don't deinterlace, passthrough frame
		
	else
		deinterlace using Avisynth field order
		
}
```
	
	
This is how my Sony DVD player behaves when playing that laundry sequence from the disc.   It results in progressive output on all frames, EXCEPT the 2 combed frames on scene change which get deinterlaced, because just for those 2 combed frames the _FieldBased prop changes to TFF.    The rest of the frames are progressive (soft telecine) so they don't need deinterlacing.    

The same Sony DVD player on hard telecined content uses mocomp deinterlacing on ALL frames, so the progressive frames on the soft telecine content is definitely not being IVTC'd by the DVD player -- it really must be looking at frame flags and making the decision based on that.

**Comment by Asd-g** [comment]
When double  rate mode is used the frame with `_FieldBased=0` is repeated?

**Comment by flossy83** [comment]
It appears so.  

24p soft telecine is doubled to 48p after bwdif and I step through 2 frames for each new image.

**Comment by Asd-g** [comment]
Try the latest version 1.2.4. It has new parameter `pass`.

**Comment by flossy83** [comment]
Thanks a lot, it seems to be working correctly for my DVDs which flag their frames as progressive.
