### ISSUE TITLE
Field order problem with BFF video?

### ISSUE THREAD

**Issue by flossy83** [Asd-g/AviSynth-BWDIF#5]
I think there may be an issue when bwdif is weaving BFF (bottom field first) video.  I am not sure if it's just inherent to the way bwdif works, but it doesn't seem to have the issue with TFF video, so I'm thinking it's somehow related to BFF.

The problem seems to be made more visible when using a `thr` value >0, such as 2 or 3, but I think the image is still wrong even when using thr=0. 

It is difficult to spot in motion, but if you pause and step through the frames you'll see it like [this](https://i3.lensdump.com/i/R5L4oo.png) (taken from test clip [here](https://drive.google.com/file/d/1Tbb0t0qFkENI5RMpm6nSAv62iqhLKdSU/view?usp=sharing), which is BFF 3-2 hard telecine).

It doesn't appear to be an issue with TFF 3-2 hard telecine: screenshot [here](https://i2.lensdump.com/i/R5Lp89.png) , test clip [here](https://drive.google.com/file/d/1wMDBU_0lAQte54qbwWMDp7qO9rgeEm2c/view?usp=share_link).

**Is it possible that bwdif makes a wrong assumption about field order when weaving BFF video?**

From what I can gather, TFF 3-2 has fields like this:
Field 1: AABCD 
Field 2: ABCCD 

BFF 3-2 would have fields like this?
Field 1: ABCCD
Field 2: AABCD

So maybe frames 2 & 3 are confusing bwdif's weaving logic somehow... I'm not sure, but TDeint & Yadif does not have this issue.

Again, it could be something inherent to the way bwdif works, I don't really know, but just wanted to report it in case it was some simple thing like a wrong field order assumption in the code.

**Comment by Asd-g** [comment]
> It is difficult to spot in motion, but if you pause and step through the frames you'll see it like [this](https://i3.lensdump.com/i/R5L4oo.png) (taken from test clip [here](https://drive.google.com/file/d/1Tbb0t0qFkENI5RMpm6nSAv62iqhLKdSU/view?usp=sharing), which is BFF 3-2 hard telecine).

For that specific frame yadifmod2 gives pretty much identical result to bwdif. TDeint gives a slight background difference - is that what you're referring to?

**Comment by flossy83** [comment]
Hmm that's different to what I'm seeing:
[bwdif(field=-2, thr=2)](https://i2.lensdump.com/i/T2SPYe.png)
[yadifmod2(mode=1)](https://i1.lensdump.com/i/T2SF2k.png)
[TDeint(mode=1)](https://i3.lensdump.com/i/T2SUCx.png)

At first I thought the problem is because I set thr=2, but even with thr=0 it's not quite right - compare it to bob() below - the aliasing on her collar in the bwdif screenshot is not really field interpolation, it looks more like some sort of artefact of bwdif weaving/blending with the wrong field:
[bwdif(field=-2, thr=0)](https://i1.lensdump.com/i/T2ScSH.png)
[bob()](https://i2.lensdump.com/i/T2SXx1.png)

Again, I would accept this as a quirk or characteristic of how bwdif works, but the fact it doesn't occur with TFF video makes me think it's something to do with field order.  Or maybe bwdif just isn't designed to work well with BFF video due to the nature of how bwdif analyses the frames?  Only someone who knows how bwdif works under the hood could answer that definitively, I think.

**Comment by Asd-g** [comment]
Indeed there was bug when processing BFF. Thanks for the report. Try the new version.

**Comment by flossy83** [comment]
Great, thank you.

[bwdif(field=-2, thr=0) previous build](https://i1.lensdump.com/i/T2ScSH.png)
[bwdif(field=-2, thr=0) current build](https://i1.lensdump.com/i/TAoj7o.png)

[bwdif(field=-2, thr=2) previous build](https://i2.lensdump.com/i/T2SPYe.png)
[bwdif(field=-2, thr=2) current build](https://i.lensdump.com/i/TAo0U9.png)
[TDeint(mode=1, mtnmode=1, slow=2)](https://i3.lensdump.com/i/TAoZZ2.png)
