### ISSUE TITLE
BWDIF setting strange field order of its output frames

### ISSUE THREAD

**Issue by flossy83** [Asd-g/AviSynth-BWDIF#7]
BWDIF appears to be setting the Avisynth internal field order of its output clip to strange/unexpected values.

I'm deleting the _FieldBased frame prop beforehand so it's not getting copy pasted from there.

Normally it shouldn't matter as the output clip doesn't need any further deinterlacing which could be affected by field order, but I was surprised to find it's causing problems with QTGMC(InputType=2) "progressive repair" mode.

To reproduce it here's an entirely TFF clip:  https://drive.google.com/file/d/1KdE0np8016zr7ovRassdbH7OtbKU7e-a/view?usp=sharing

```
LWLibavVideoSource(filepath, stream_index=-1, repeat=true)
propDelete("_FieldBased").bwdif(field=-2)
info() 
```

Info() is showing at around the 47 second mark BWDIF has for some reason changed it to BFF:

![problem 2](https://github.com/Asd-g/AviSynth-BWDIF/assets/46382337/ce33431d-efe9-474d-b570-64955efc909e)

And now if I try a QTGMC progressive repair on it like this I get these blended stuttering frames:

```
LWLibavVideoSource(clip, stream_index=-1, repeat=true)
propDelete("_FieldBased").bwdif(field=-2, thr=2.0)
QTGMC(InputType=2, Preset="slow", TR2=1, EdiThreads=2).Prefetch(4)
```

![problem](https://github.com/Asd-g/AviSynth-BWDIF/assets/46382337/704d0ff7-0f58-42af-a80c-37e5dae036b7)

Easily resolved with AssumeTFF() after BWDIF - it seems QTGMC's progressive repair modes need a constant field order to work properly, which is what the output of BWDIF should be.

**Comment by flossy83** [comment]
It seems TDeint has the same behaviour, so I'm guessing this must be some kind of intentional behaviour to tell possible filters downstream which field contains the interpolated pixels or something?

**Comment by Asd-g** [comment]
This is not intentional behaviour (at least for BWDIF).

Try the attached test version.

[BWDIF.zip](https://github.com/Asd-g/AviSynth-BWDIF/files/12610831/BWDIF.zip)

**Comment by flossy83** [comment]
Thanks that seems to have resolved it.
